### ISSUE TITLE
Add check on Bridge page for already token approval

### ISSUE THREAD

**Issue by mogithehurt** [subquery/network-app#676]
when we do eth to base bridge 
txn 1. token approval
txn 2. if we cancel 2 nd txn it redirect to again 1st txn (this is not required because we already approved it only hurts for gas) 
 if you can hardcode gas limit for 2nd txn please hardcode it to 200000 or 250000

**Comment by HuberTRoy** [comment]
Thanks for your feedback~. 

I have added the check for token approval.

The wallet supplied custom gas price & gas limit feature. I'm not sure if necessary to hardcode it, keep the status quo.
