### ISSUE TITLE
error on Redelegate

### ISSUE THREAD

**Issue by mogithehurt** [subquery/network-app#684]
i was going to Redelegate to another Indexer and found this error.
![image](https://github.com/subquery/network-app/assets/114102465/70266827-78d3-4bc8-8ff0-5e063ea6e21f)

**Comment by HuberTRoy** [comment]
@mogithehurt 

Thanks for the feedback~. Seems it's a bug of `Max` button. Will fix it later. You can input the value manually for now.

**Comment by mogithehurt** [comment]
@HuberTRoy Right, manually worked. Thanks.
