### ISSUE TITLE
Data is not loading on direct URL browsing 

### ISSUE THREAD

**Issue by mogithehurt** [subquery/network-app#691]
https://app.subquery.network/indexer/0xd5d39c5d46d973c1c824877d9a583fd2e4a39c11 
![image](https://github.com/subquery/network-app/assets/114102465/e32db913-1478-4587-be91-ac1838ab6fbd)
but is works perfect in home page>delegator>indexer page 
![image](https://github.com/subquery/network-app/assets/114102465/23028adb-665d-48e7-9bab-f4f0084f39c7)

**Comment by HuberTRoy** [comment]
Thanks~, will fix at next release.

**Comment by HuberTRoy** [comment]
Fixed at #693
