### ISSUE TITLE
i have sqt in base but ui is saying it is on eth

### ISSUE THREAD

**Issue by mogithehurt** [subquery/network-app#696]
Metamask network status: Base 
https://app.subquery.network/indexer/0x82aada6f7adedc1b68bdfa40d09581d6bb65ef76
![image](https://github.com/subquery/network-app/assets/114102465/6d4a8764-bb79-400f-9c59-4f5cece1628e)

**Comment by mogithehurt** [comment]
Remaining Delegation Capacity 0.0 SQT oh i see there is no more capacity , please handle this case more user friendly

**Comment by HuberTRoy** [comment]
What problem here? 

The tooltip to tips you have what amount of SQT on eth. It's showing `0.0000` and actually you don't have SQT on eth, so it's right= =?

The second problem will do. Thanks for your report~.
